config/routes.rb
Rails.application.routes.draw do

  root "site#index"

  scope '/' do
    get '/trabalhe-conosco',  to: 'curriculums#new'
    get '/trajetoria',        to: 'site#trajetoria'
    get '/areas-atuacao',     to: 'site#areas-atuacao'
    get '/carreiras',         to: 'site#carreiras'
    get '/obras',             to: 'site#obras'
    resources :curriculums, path: 'trabalhe-conosco', only: [:new, :create]
  end

  scope '/gestao' do



    devise_for :users, controllers: {
      sessions: 'sessions'
    }

    authenticate :user do
      
      resources :reports, path: 'relatorios' do 
        collection do  
          get 'fornecedores/:project_id', to: 'reports#suppliers',  as: 'suppliers'
          get 'funcionarios/:project_id', to: 'reports#staffs',     as: 'staffs'
          get 'veiculos/:project_id',     to: 'reports#vehicles',   as: 'vehicles'
          get 'caixa-contas/:project_id', to: 'reports#finances',    as: 'finances'
        end
      end

      resources :users, path: 'usuarios'

      get '/', to: 'dashboard#index'

      resources :passwords, path: 'trocar_senha', only: [:edit, :update]
      resources :project_categories, path: 'categorias_obra'

      resources :projects, path: 'obras' do
        resources :project_finances, path: 'caixa'
        resources :project_funds, path: 'gastos'
        resources :staff_funds, path: 'funcionario_entradas'
        resources :staff_pays, path: 'funcionario_gastos'
        resources :vehicles, path: 'veículos'
        resources :archives, path: 'arquivos'
        resources :fuel_expenses, path: 'consumo'
        resources :quotations, path: 'cotacoes' do
          resources :budgets, path: 'orcamentos'
        end
        resources :pays, path: 'contas_pagar'
        resources :receipts, path: 'contas_receber'
        resources :suppliers, path: 'fornecedores'
      end

      resources :bill_categories, path: 'categorias_conta'
      resources :offices, path: 'escritorios'
      resources :office_supports, path: 'ponto de apoio'
      resources :supplier_categories, path: 'categorias_fornecedor'
      resources :staffs, path: 'funcionarios'
      resources :vehicle_services, path: 'servicos_veiculo'
      resources :vehicle_categories, path: 'categoria_veiculo'
      resources :sectors, path: 'setores'
      resources :jobs, path: 'cargos'
      resources :beneficts, path: 'beneficios'

    end
  end
end

app/models/staff.rb
class Staff < ActiveRecord::Base
  belongs_to :job
  belongs_to :sector
  belongs_to :project
  belongs_to :office
  belongs_to :office_support


  validates_presence_of :name, :code, :cpf, :job, :city, :state, :telphone, :born
  validates :telphone, numericality: true
  validates :salary, allow_blank: true, numericality: { only_float: true }
  validates_numericality_of :telphone_optional, :celphone, allow_blank: true
  validates :cpf, cpf: true
  validates_date :born

end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]
  #before_action :set_project
  # GET /staffs
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  def create
    @staff = Staff.new(staff_params)

    if @staff.save
      flash[:success] = t :success
      redirect_to action: 'index'
    else
      render :new
    end
  end

  # PATCH/PUT /staffs/1
  def update
    if @staff.update(staff_params)
      flash[:success] = t :success
      redirect_to action: 'index'    
    else
      render :edit
    end
  end

  # DELETE /staffs/1
  def destroy
    if @staff.destroy
      flash[:success] = t :success
      redirect_to action: 'index'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def staff_params
      params.require(:staff).permit(:name, :code, :cpf, :job_function, :job_id, :status, :sector_id, :city, :state, :address, :telphone, :telphone_optional, :celphone, :project_id, :office_id, :office_support_id, :born, :salary)
    end

    def set_project
      @project = Project.find(params[:project_id])
    end
end

app/views/staffs/_form.html.haml
= simple_form_for(@staff) do |f|
  = f.error_notification

  .row
    .col-md-8
      = f.input :name
    .col-md-2
      = f.input :code
    .col-md-2
      = f.input :cpf
  .row
    .col-md-2
      = f.association :job, prompt: 'selecione o cargo...'
    .col-md-2
      = f.input :job_function
    .col-md-2
      = f.association :sector, prompt: 'selecione o setor...'
    .col-md-2
      = f.input :telphone
    .col-md-2
      = f.input :telphone_optional
    .col-md-2
      = f.input :celphone
  %hr/
  .row
    .col-md-4
      = f.input :city
    .col-md-2
      = f.input :state
  .row
    .col-md-12
      = f.input :address
  %hr/
  .row
    .col-md-2
      = f.input :born, as: 'string', input_html: { class: 'date', value: (f.object.born.present?) ? localize(f.object.born) : nil }
    .col-md-2
      = f.input :salary, as: :string, input_html: { class: "coin_mask"}
    .col-md-3
      = f.input :status, as: :select, include_blank: false
    .col-md-3
      = f.input :driver, as: :select, include_blank: false
  %hr/
  .row
    .col-md-12
      = f.button :submit, class: 'btn btn-success'
      = link_to "Voltar", staffs_path, class: 'btn btn-default'

app/views/staffs/edit.html.haml
.row
  .col-sm-12
    %section.panel
      %header.panel-heading
        Editar funcionário
        = link_to 'Voltar', staffs_path, class: 'btn btn-default btn-xs pull-right'
      .panel-body
        = render 'form'

app/views/staffs/index.html.haml
.row
  .col-sm-12
    %section.panel
      %header.panel-heading
        funcionários
        = link_to '<b>Novo funcionário</b>'.html_safe, new_staff_path, class: 'btn btn-success btn-xs pull-right'
      .panel-body

        %table.table.table-hover.table-condensed.datatable
          %thead
            %tr
              %th
                nome
              %th
                matrícula
              %th
                cargo
              %th
                sector
              %th
                telefone
              %th
                projeto
              %th
                status
              %th.col-md-2
                ações
          %tbody
            - @staffs.each do |staff|
              %tr

                %td.col-md-4
                  =staff.name
                %td
                  =staff.code
                %td
                  =staff.job.name if staff.job.present?
                %td
                  =staff.sector.acron if staff.sector.present?
                %td
                  =staff.telphone
                %td
                  =staff.project.name if staff.project.present?
                %td
                  =status_helper staff.status
                %td.col-md-2
                  = link_to 'Editar', edit_staff_path(staff), class: 'btn btn-info btn-xs'
                  = link_to 'Remover', staff, :method => :delete, :data => { :confirm => t(:confirm_remove) }, class: 'btn btn-danger btn-xs'

app/views/staffs/new.html.haml
.row
  .col-sm-12
    %section.panel
      %header.panel-heading
        Novo funcionário
        = link_to 'Voltar', staffs_path, class: 'btn btn-default btn-xs pull-right'
      .panel-body
        = render 'form'

app/views/staffs/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @staff.name
%p
  %b Code:
  = @staff.code
%p
  %b Cpf:
  = @staff.cpf
%p
  %b Job function:
  = @staff.job_function
%p
  %b Job:
  = @staff.job
%p
  %b Status:
  = @staff.status
%p
  %b Sector:
  = @staff.sector
%p
  %b City:
  = @staff.city
%p
  %b State:
  = @staff.state
%p
  %b Address:
  = @staff.address
%p
  %b Telphone:
  = @staff.telphone
%p
  %b Telphone optional:
  = @staff.telphone_optional
%p
  %b Celphone:
  = @staff.celphone
%p
  %b Project:
  = @staff.project
%p
  %b Office:
  = @staff.office
%p
  %b Office support:
  = @staff.office_support
%p
  %b Born:
  = @staff.born
%p
  %b Salary:
  = @staff.salary

= link_to 'Edit', edit_staff_path(@staff)
\|
= link_to 'Back', staffs_path