config/routes.rb
Rails.application.routes.draw do

  root "site#index"

  scope '/' do
    get '/trabalhe-conosco',  to: 'curriculums#new'
    get '/trajetoria',        to: 'site#trajetoria'
    get '/areas-atuacao',     to: 'site#areas-atuacao'
    get '/carreiras',         to: 'site#carreiras'
    get '/obras',             to: 'site#obras'
    resources :curriculums, path: 'trabalhe-conosco', only: [:new, :create]
  end

  scope '/gestao' do



    devise_for :users, controllers: {
      sessions: 'sessions'
    }

    authenticate :user do
      
      resources :reports, path: 'relatorios' do 
        collection do  
          get 'fornecedores/:project_id', to: 'reports#suppliers',  as: 'suppliers'
          get 'funcionarios/:project_id', to: 'reports#staffs',     as: 'staffs'
          get 'veiculos/:project_id',     to: 'reports#vehicles',   as: 'vehicles'
          get 'caixa-contas/:project_id', to: 'reports#finances',    as: 'finances'
        end
      end

      resources :users, path: 'usuarios'

      get '/', to: 'dashboard#index'

      resources :passwords, path: 'trocar_senha', only: [:edit, :update]
      resources :project_categories, path: 'categorias_obra'

      resources :projects, path: 'obras' do
        resources :project_finances, path: 'caixa'
        resources :project_funds, path: 'gastos'
        resources :staff_funds, path: 'funcionario_entradas'
        resources :staff_pays, path: 'funcionario_gastos'
        resources :vehicles, path: 'veículos'
        resources :archives, path: 'arquivos'
        resources :fuel_expenses, path: 'consumo'
        resources :quotations, path: 'cotacoes' do
          resources :budgets, path: 'orcamentos'
        end
        resources :pays, path: 'contas_pagar'
        resources :receipts, path: 'contas_receber'
        resources :suppliers, path: 'fornecedores'
      end

      resources :bill_categories, path: 'categorias_conta'
      resources :offices, path: 'escritorios'
      resources :office_supports, path: 'ponto de apoio'
      resources :supplier_categories, path: 'categorias_fornecedor'
      resources :staffs, path: 'funcionarios'
      resources :vehicle_services, path: 'servicos_veiculo'
      resources :vehicle_categories, path: 'categoria_veiculo'
      resources :sectors, path: 'setores'
      resources :jobs, path: 'cargos'
      resources :beneficts, path: 'beneficios'

    end
  end
end

app/models/quotation.rb
class Quotation < ActiveRecord::Base
  belongs_to :project
  belongs_to :responsible, class_name: "Staff"

  has_many :budgets
  
  validates_presence_of :name, :date
end

app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController
  before_action :set_project
  before_action :set_quotation, only: [:show, :edit, :update, :destroy]

  # GET /quotations
  def index
    @quotations = @project.quotations.all
  end

  # GET /quotations/1
  def show
  end

  # GET /quotations/new
  def new
    @quotation = @project.quotations.new
  end

  # GET /quotations/1/edit
  def edit
  end

  # POST /quotations
  def create
    @quotation = @project.quotations.new(quotation_params)

    if @quotation.save
      flash[:success] = t :success
      redirect_to action: 'index'
    else
      render :new
    end
  end

  # PATCH/PUT /quotations/1
  def update
    if @quotation.update(quotation_params)
      flash[:success] = t :success
      redirect_to action: 'index'
    else
      render :edit
    end
  end

  # DELETE /quotations/1
  def destroy
    if @quotation.destroy
      flash[:success] = t :success
      redirect_to action: 'index'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quotation
      @quotation = @project.quotations.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    # Only allow a trusted parameter "white list" through.
    def quotation_params
      params.require(:quotation).permit(:name, :description, :date, :project_id, :responsible_id, :status)
    end
end

app/views/quotations/_form.html.haml
= simple_form_for([@project, @quotation]) do |f|
  = f.error_notification

  .row
    .col-md-12
      = f.input :name
  .row
    .col-md-12
      = f.input :description
  .row
    .col-md-2
      = f.input :date, as: 'string', input_html: { class: 'date', value: (f.object.date.present?) ? localize(f.object.date) : nil }
    .col-md-4
      = f.association :responsible, prompt: 'selecione...'
    .col-md-4
      %br/
      = f.input :status
  %hr/
  .row
    .col-md-12
      = f.button :submit, class: 'btn btn-success'

app/views/quotations/edit.html.haml
.row
  .col-sm-12
    %section.panel
      %header.panel-heading
        editar cotação
        = link_to 'Voltar', project_quotations_path(@project), class: 'btn btn-default btn-xs pull-right'
      .panel-body
        = render 'form'

app/views/quotations/index.html.haml
.row
  .col-sm-12
    %section.panel
      %header.panel-heading
        Cotações
        = link_to 'Nova cotação', new_project_quotation_path(@project), class: 'btn btn-success btn-xs pull-right'
      .panel-body

        %table.table.table-hover.general-table.datatable
          %thead
            %tr
              %th.col-md-2 Nome
              %th.col-md-2 Descrição
              %th.col-md-2 Data
              %th.col-md-2 Responsável
              %th.col-md-2 Ações
          %tbody
            - @quotations.each do |quotation|
              %tr
                %td.col-md-3
                  = link_to quotation.name
                %td.col-md-3
                  =quotation.description
                %td.col-md-1
                  =quotation.date.strftime("%d/%m/%Y")
                %td.col-md-2
                  =quotation.responsible if quotation.responsible.present?
                %td.col-md-3
                  = link_to 'Visualizar', project_quotation_budgets_path(project_id: @project, quotation_id: quotation), class: 'btn btn-success btn-xs'
                  = link_to 'Editar', edit_project_quotation_path(project_id: @project, id: quotation), class: 'btn btn-info btn-xs'
                  = link_to 'Remover', project_quotation_path(project_id: @project, id:quotation), :method => :delete, :data => { :confirm => t(:confirm_remove) }, class: 'btn btn-danger btn-xs'

app/views/quotations/new.html.haml
.row
  .col-sm-12
    %section.panel
      %header.panel-heading
        Nova cotação
        = link_to 'Voltar', project_quotations_path(@project), class: 'btn btn-default btn-xs pull-right'
      .panel-body
        = render 'form'

app/views/quotations/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @quotation.name
%p
  %b Description:
  = @quotation.description
%p
  %b Date:
  = @quotation.date
%p
  %b Project:
  = @quotation.project
%p
  %b Responsible:
  = @quotation.responsible
%p
  %b Status:
  = @quotation.status

= link_to 'Edit', edit_quotation_path(@quotation)
\|
= link_to 'Back', quotations_path