config/routes.rb
Rails.application.routes.draw do

  root "site#index"

  scope '/' do
    get '/trabalhe-conosco',  to: 'curriculums#new'
    get '/trajetoria',        to: 'site#trajetoria'
    get '/areas-atuacao',     to: 'site#areas-atuacao'
    get '/carreiras',         to: 'site#carreiras'
    get '/obras',             to: 'site#obras'
    resources :curriculums, path: 'trabalhe-conosco', only: [:new, :create]
  end

  scope '/gestao' do



    devise_for :users, controllers: {
      sessions: 'sessions'
    }

    authenticate :user do
      
      resources :reports, path: 'relatorios' do 
        collection do  
          get 'fornecedores/:project_id', to: 'reports#suppliers',  as: 'suppliers'
          get 'funcionarios/:project_id', to: 'reports#staffs',     as: 'staffs'
          get 'veiculos/:project_id',     to: 'reports#vehicles',   as: 'vehicles'
          get 'caixa-contas/:project_id', to: 'reports#finances',    as: 'finances'
        end
      end

      resources :users, path: 'usuarios'

      get '/', to: 'dashboard#index'

      resources :passwords, path: 'trocar_senha', only: [:edit, :update]
      resources :project_categories, path: 'categorias_obra'

      resources :projects, path: 'obras' do
        resources :project_finances, path: 'caixa'
        resources :project_funds, path: 'gastos'
        resources :staff_funds, path: 'funcionario_entradas'
        resources :staff_pays, path: 'funcionario_gastos'
        resources :vehicles, path: 'veículos'
        resources :archives, path: 'arquivos'
        resources :fuel_expenses, path: 'consumo'
        resources :quotations, path: 'cotacoes' do
          resources :budgets, path: 'orcamentos'
        end
        resources :pays, path: 'contas_pagar'
        resources :receipts, path: 'contas_receber'
        resources :suppliers, path: 'fornecedores'
      end

      resources :bill_categories, path: 'categorias_conta'
      resources :offices, path: 'escritorios'
      resources :office_supports, path: 'ponto de apoio'
      resources :supplier_categories, path: 'categorias_fornecedor'
      resources :staffs, path: 'funcionarios'
      resources :vehicle_services, path: 'servicos_veiculo'
      resources :vehicle_categories, path: 'categoria_veiculo'
      resources :sectors, path: 'setores'
      resources :jobs, path: 'cargos'
      resources :beneficts, path: 'beneficios'

    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :project_category
  belongs_to :responsible, class_name: 'Staff'

  has_many :pays
  has_many :receipts
  has_many :quotations
  has_many :vehicles
  has_many :gas_stations
  has_many :fuel_expenses
  has_many :archives
  has_many :project_finances
  has_many :suppliers
  has_many :project_funds

  validates_presence_of :name, :local, :priority


  enum :priority => [:alta, :media, :baixa]
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  def index
    @projects = Project.all
  end

  # GET /projects/1
  def show

    if params[:search].present?
      @begin_month  = Date.parse(params[:search][:start_date].to_s)
      @end_month    = Date.parse(params[:search][:end_date].to_s)
    else
      @begin_month  = Date.today.beginning_of_month
      @end_month    = Date.today.end_of_month
    end

    @project_funds   = @project.project_funds.where(date_payment: @begin_month..@end_month)
    @project_finance = @project.project_finances.where(date: @begin_month..@end_month)
    @pays            = @project.pays.where(deadline: @begin_month..@end_month, status: false)
    @receipts        = @project.receipts.where(deadline: @begin_month..@end_month, status: false)
    @fuels           = @project.fuel_expenses.where(date: @begin_month..@end_month)
    @uploads         = @project.archives.limit(10).order('created_at DESC')
            
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  def create
    @project = Project.new(set_params)

    if @project.save
      redirect_to action: 'index'
      flash[:success] = t :success
    else
      render :new
    end
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(set_params)
      flash[:success] = t :success
      redirect_to action: 'index'
    else
      render :edit
    end
  end

  # DELETE /projects/1
  def destroy
    if @project.destroy
        flash[:success] = t :success
        redirect_to action: 'index'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def set_params
      params.require(:project).permit(:project_category_id, :name, :local, :responsible_id, :geolocation, :description, :observation, :priority)
    end
end

app/views/projects/_form.html.haml
= simple_form_for(@project) do |f|
  = f.error_notification

  .row
    .col-md-6
      = f.association :project_category, prompt: 'selecione a categoria...'
    .col-md-6
      = f.input :priority, as: 'select', collection: Project.priorities.keys.to_a, prompt: 'selecione...'
  .row
    .col-md-12
      = f.input :name
  .row
    .col-md-12
      = f.input :description
  .row
    .col-md-4
      = f.input :local
    .col-md-4
      = f.input :geolocation
    .col-md-4
      = f.association :responsible, prompt: 'selecione...'
  .row
    .col-md-12
      = f.input :observation
  %hr/
  .row
    .col-md-12
      = f.button :submit, class: 'btn btn-success'

app/views/projects/edit.html.haml
.row
  .col-sm-12
    %section.panel
      %header.panel-heading
        Editar project
        = link_to 'Voltar', projects_path, class: 'btn btn-default btn-xs pull-right'
      .panel-body
        = render 'form'

app/views/projects/index.html.haml
.row
  - @projects.where(id: current_user.project_privilege_id).each do |project|
    .col-md-3
      %section.panel
        %header.panel-heading
          %b= project.project_category.name if project.project_category.present?
          %span.tools.pull-right
            = link_to "", edit_project_path(project), class: 'btn-xs fa fa-cog'
            = link_to "", project_path(project),method: :delete,  class: 'btn-xs fa fa-times'

        .panel-body
          .row
            .col-md-12
              %h1
                %b= project.name
              %h5
                = project.description
          %hr/
          .row
            .col-md-12
              %b= link_to "Gerênciar Obra", project_path(project), class: 'btn btn-success btn-sm'
              %b= link_to "Gerênciar Caixa", project_project_finances_path(project), class: 'btn btn-warning btn-sm'
      

app/views/projects/new.html.haml
.row
  .col-sm-12
    %section.panel
      %header.panel-heading
        Nova project
        = link_to 'Voltar', projects_path, class: 'btn btn-default btn-xs pull-right'
      .panel-body
        = render 'form'

app/views/projects/show.html.haml
.row
  .col-sm-12
    %section.panel
      %header.panel-heading
        Filtro
      .panel-body
        .row
          .col-md-12
            = simple_form_for :search, url: project_path(@project), :method => 'get' do |f|
              .col-md-2
                = f.label "Data inicial"
                = f.input :start_date, label:false, as: :string, input_html: { class: 'date', value: params[:search].present? ? params[:search][:start_date] : @begin_month.strftime('%d/%m/%Y')}
              .col-md-2
                = f.label "Data final"
                = f.input :end_date, label:false, as: :string, input_html: { class: 'date', value: params[:search].present? ? params[:search][:end_date] : @end_month.strftime('%d/%m/%Y')}
              .col-md-2{style: 'margin-top: 23px'}
                = f.submit "Filtrar Resultados", class: 'btn btn-success btn-sm'
.row
  .col-md-3
    .mini-stat.clearfix
      %span.mini-stat-icon.orange
        %i.fa.fa-gavel
      .mini-stat-info
        %span= number_to_currency((@pays.present?) ? @pays.sum(:value) : 0.00, unit: "R$", separator: ",", delimiter: "") 
        Contas à pagar
  .col-md-3
    .mini-stat.clearfix
      %span.mini-stat-icon.tar
        %i.fa.fa-tag
      .mini-stat-info
        %span= number_to_currency((@receipts.present?) ? @receipts.sum(:value) : 0.00, unit: "R$", separator: ",", delimiter: "") 
        Contas à receber
  .col-md-3
    .mini-stat.clearfix
      %span.mini-stat-icon.pink
        %i.fa.fa-money
      .mini-stat-info
        %span= number_to_currency(((@project_finance.present?) ? @project_finance.sum(:value) : 0.00) - ((@project_funds.present?) ? @project_funds.sum(:value) : 0.00), unit: "R$", separator: ",", delimiter: "") 
        Saldo em Caixa 
  .col-md-3
    .mini-stat.clearfix
      %span.mini-stat-icon.green
        %i.fa.fa-eye
      .mini-stat-info
        %span= number_to_currency((@project_funds.present?) ? @project_funds.sum(:value) : 0.00, unit: "R$", separator: ",", delimiter: "") 
        Gastos do Caixa
.row
  .col-sm-6
    %section.panel
      %header.panel-heading
        Últimas Contas À PAGAR Lançadas
        %span.tools.pull-right
          %a.fa.fa-cog{:href => "javascript:;"}
      .panel-body
        %table.table
          %thead
            %tr
              %th Título
              %th Fornecedor
              %th Vencimento
              %th valor
              %th Status
          %tbody
            - @pays.each_with_index do |p, i|
              %tr
                %td.col-md-4= link_to p.name, edit_project_pay_path(project_id: p.project, id: p)
                %td.col-md-4= link_to p.supplier.name, project_supplier_path(project_id: p.project, id: p.supplier) if p.supplier.present?
                %td.col-md-2= p.deadline.strftime('%d/%m/%Y')
                %td.col-md-2
                  = number_to_currency p.value
                %td.col-md-2
                  - if p.deadline < Date.today && !p.status
                    %span.label.label-danger
                      Vencida
                  - elsif p.status
                    %span.label.label-success
                      Pago
                  - else
                    %span.label.label-success
                      À vencer
                
  .col-sm-6
    %section.panel
      %header.panel-heading
        Últimos Lançamentos em caixa
        %span.tools.pull-right
          %a.fa.fa-chevron-down{:href => "javascript:;"}
          %a.fa.fa-cog{:href => "javascript:;"}
          %a.fa.fa-times{:href => "javascript:;"}
      .panel-body
        %table.table.table-striped
          %thead
            %tr
              %th #
              %th Título
              %th Fornecedor
              %th Data de lançamento
              %th Valor
          %tbody
            - @project_funds.each_with_index do |f,i|
              %tr
                %td.col-md-1= i + 1
                %td.col-md-3= f.name
                %td.col-md-3= link_to f.supplier.name, project_supplier_path(project_id: f.project, id: f.supplier) if f.supplier.present?
                %td.col-md-2= f.created_at.strftime('%d/%m/%Y')
                %td.col-md-1
                  %span.label.label-info
                    = number_to_currency(f.value, unit: "R$", separator: ",", delimiter: "")
.row
  .col-sm-6
    %section.panel
      %header.panel-heading
        Últimos Abastecimento de veículos
        %span.tools.pull-right
          %a.fa.fa-chevron-down{:href => "javascript:;"}
          %a.fa.fa-cog{:href => "javascript:;"}
          %a.fa.fa-times{:href => "javascript:;"}
      .panel-body
        %table.table
          %thead
            %tr
              %th #
              %th Veículo
              %th Posto de abastecimento
              %th Valor Total
          %tbody
            - @fuels.each_with_index do |f, i|
              %tr
                %td= i + 1
                %td= f.vehicle.name
                %td= link_to f.supplier.name, project_supplier_path(project_id: f.project, id: f.supplier) if f.supplier.present?
                %td= number_to_currency(f.fuel_lt * f.fuel_price_lt)

  .col-sm-6
    %section.panel
      %header.panel-heading
        Últimos uploads da obra
        %span.tools.pull-right
          %a.fa.fa-chevron-down{:href => "javascript:;"}
          %a.fa.fa-cog{:href => "javascript:;"}
          %a.fa.fa-times{:href => "javascript:;"}
      .panel-body
        %table.table.table-striped
          %thead
            %tr
              %th #
              %th Título
              %th Data
              %th Arquivo
          %tbody
          - @uploads.each_with_index do |u, i|
            %tr
              %td= i + 1 
              %td= u.name
              %td= u.created_at.strftime('%d/%m/%Y')
              %td= link_to "Baixar", u.file_path.url
  