config/routes.rb
Rails.application.routes.draw do

  root "site#index"

  scope '/' do
    get '/trabalhe-conosco',  to: 'curriculums#new'
    get '/trajetoria',        to: 'site#trajetoria'
    get '/areas-atuacao',     to: 'site#areas-atuacao'
    get '/carreiras',         to: 'site#carreiras'
    get '/obras',             to: 'site#obras'
    resources :curriculums, path: 'trabalhe-conosco', only: [:new, :create]
  end

  scope '/gestao' do



    devise_for :users, controllers: {
      sessions: 'sessions'
    }

    authenticate :user do
      
      resources :reports, path: 'relatorios' do 
        collection do  
          get 'fornecedores/:project_id', to: 'reports#suppliers',  as: 'suppliers'
          get 'funcionarios/:project_id', to: 'reports#staffs',     as: 'staffs'
          get 'veiculos/:project_id',     to: 'reports#vehicles',   as: 'vehicles'
          get 'caixa-contas/:project_id', to: 'reports#finances',    as: 'finances'
        end
      end

      resources :users, path: 'usuarios'

      get '/', to: 'dashboard#index'

      resources :passwords, path: 'trocar_senha', only: [:edit, :update]
      resources :project_categories, path: 'categorias_obra'

      resources :projects, path: 'obras' do
        resources :project_finances, path: 'caixa'
        resources :project_funds, path: 'gastos'
        resources :staff_funds, path: 'funcionario_entradas'
        resources :staff_pays, path: 'funcionario_gastos'
        resources :vehicles, path: 'veículos'
        resources :archives, path: 'arquivos'
        resources :fuel_expenses, path: 'consumo'
        resources :quotations, path: 'cotacoes' do
          resources :budgets, path: 'orcamentos'
        end
        resources :pays, path: 'contas_pagar'
        resources :receipts, path: 'contas_receber'
        resources :suppliers, path: 'fornecedores'
      end

      resources :bill_categories, path: 'categorias_conta'
      resources :offices, path: 'escritorios'
      resources :office_supports, path: 'ponto de apoio'
      resources :supplier_categories, path: 'categorias_fornecedor'
      resources :staffs, path: 'funcionarios'
      resources :vehicle_services, path: 'servicos_veiculo'
      resources :vehicle_categories, path: 'categoria_veiculo'
      resources :sectors, path: 'setores'
      resources :jobs, path: 'cargos'
      resources :beneficts, path: 'beneficios'

    end
  end
end

app/views/layouts/partials/_nav.html.haml
%header.header.fixed-top.clearfix
  / logo start
  .brand
    = link_to image_tag("henz_logo.jpg", width: 170, height: 80), root_path
  .horizontal-menu.navbar-collapse.collapse
    %ul.nav.navbar-nav
      %li
        = link_to "início", '/gestao'
      %li.dropdown
        %a.dropdown-toggle{"data-hover" => "dropdown", "data-toggle" => "dropdown", :href => "#"}
          Obras
          %b.fa.fa-angle-down
        %ul.dropdown-menu
          
          - if policy(:application).administrador? || policy(:application).gerente?
            %li
              = link_to "Visualizar Obras", projects_path
          - if policy(:application).administrador?
            %li
              = link_to "Nova obra", new_project_path
            %li
              = link_to "Categorias", project_categories_path
          %li.divider
          - @nav_projects.each do |p|
            %li= link_to p.name, project_path(p) if current_user.project_privileges(p.id)

      - if policy(:application).administrador? || policy(:application).gerente?
        %li.dropdown
          %a.dropdown-toggle{"data-hover" => "dropdown", "data-toggle" => "dropdown", :href => "#"}
            Administração
            %b.fa.fa-angle-down
          %ul.dropdown-menu
            - if policy(:application).administrador?
              %li
                = link_to "Usuários", users_path
              %li.divider
              %li
                = link_to "Funcionários", staffs_path
              %li
                = link_to "Setores", sectors_path
              %li
                = link_to "Cargos", jobs_path
              %li.divider
            - if policy(:application).administrador? || policy(:application).gerente?
              %li
                = link_to "Serviços de veículos", vehicle_services_path
              %li
                = link_to "Categorias de veículos", vehicle_categories_path
              %li
                = link_to "Categorias de fornecedores", supplier_categories_path
              %li
                = link_to "Categorias de contas",bill_categories_path
            - if policy(:application).administrador?
              %li.divider
              %li
                = link_to "Escritórios", offices_path
              %li
                = link_to "Pontos de apoio", office_supports_path
  .horizontal-menu.navbar-collapse.collapse.pull-right
    %ul.nav.navbar-nav
      %li.dropdown
        %a.dropdown-toggle{"data-hover" => "dropdown", "data-toggle" => "dropdown", :href => "#"}
          = current_user.email
          %b.fa.fa-angle-down
        %ul.dropdown-menu
          %li
            = link_to "Trocar Senha", edit_password_path(current_user)
          %li
            = link_to "Sair", destroy_user_session_path, method: :delete

app/views/layouts/partials/_sidebar.html.haml
%aside
  #sidebar.nav-collapse
    / sidebar menu start
    .leftside-navigation{:style => "overflow: hidden; outline: none;", :tabindex => "5000"}
      %ul#nav-accordion.sidebar-menu
        %li
          %b
            = link_to "<i class='fa fa-dashboard'></i><span>Dashboard</span>".html_safe, project_path(@project)
        - if policy(:application).administrador? || policy(:application).gerente?
          %li.sub-menu.dcjq-parent-li
            %a.dcjq-parent{:href => "javascript:;"}
              %i.fa.fa-book
              %span
                %b Caixa
              %span.dcjq-icon
            %ul.sub{:style => "display: none;"}
              %li= link_to "Novo Gasto", new_project_project_fund_path(@project)
              %li= link_to "Caixa da obra", project_project_funds_path(@project)
              %li= link_to "Entradas meu caixa", project_staff_funds_path(@project)
              %li= link_to "Saídas meu caixa", project_staff_pays_path(@project)
        %li.sub-menu.dcjq-parent-li
          %a.dcjq-parent{:href => "javascript:;"}
            %i.fa.fa-laptop
            %span
              %b Contas
            %span.dcjq-icon
          %ul.sub{:style => "display: none;"}
            %li= link_to "Contas à Pagar", project_pays_path(@project)
            - if policy(:application).administrador? || policy(:application).gerente?
              %li= link_to "Contas à Receber", project_receipts_path(@project)
        - if policy(:application).administrador? || policy(:application).gerente?
          %li.sub-menu.dcjq-parent-li
            %a.dcjq-parent{:href => "javascript:;"}
              %i.fa.fa-briefcase
              %span
                %b Fornecedores
              %span.dcjq-icon
            %ul.sub{:style => "display: none;"}
              %li= link_to "Novo fornecedor", new_project_supplier_path(@project)
              %li= link_to "Gerenciar", project_suppliers_path(@project)
        %li.sub-menu.dcjq-parent-li
          %a.dcjq-parent{:href => "javascript:;"}
            %i.fa.fa-book
            %span 
              %b Cotações
            %span.dcjq-icon
          %ul.sub{:style => "display: none;"}
            %li= link_to "Nova cotação", new_project_quotation_path(@project)
            %li= link_to "Gerenciar", project_quotations_path(@project)
          %li.sub-menu.dcjq-parent-li
            %a.dcjq-parent{:href => "javascript:;"}
              %i.fa.fa-th
              %span
                %b Veículos
              %span.dcjq-icon
            %ul.sub{:style => "display: none;"}
              - if policy(:application).administrador? || policy(:application).gerente?
                %li= link_to "Gerenciar", project_vehicles_path(@project)
              %li= link_to "Consumo", project_fuel_expenses_path(@project)
        %li.sub-menu.dcjq-parent-li
          %a.dcjq-parent{:href => "javascript:;"}
            %i.fa.fa-envelope
            %span
              %b Arquivos
            %span.dcjq-icon
          %ul.sub{:style => "display: none;"}
            - if policy(:application).administrador? || policy(:application).gerente?
              %li= link_to "Novo upload", new_project_archive_path(@project)
            %li= link_to "Gerenciar", project_archives_path(@project)
        %li.sub-menu.dcjq-parent-li
          %a.dcjq-parent{:href => "javascript:;"}
            %i.fa.fa-bar-chart-o
            %span
              %b Relatórios
            %span.dcjq-icon
          %ul.sub{:style => "display: none;"}
            - if policy(:application).administrador? || policy(:application).gerente?
              %li= link_to "Fornecedores", suppliers_reports_path(@project)
              %li= link_to "Veículos", vehicles_reports_path(@project)
              %li= link_to "Contas & Caixa", finances_reports_path(@project)
            